# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='editted',
            new_name='edited',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='editted_image',
        ),
        migrations.AddField(
            model_name='picture',
            name='edited_image',
            field=models.ImageField(blank=True, upload_to='edited/'),
        ),
    ]
