# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160524_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='editted_image',
            field=models.ImageField(blank=True, upload_to='editted/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='uploaded_image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
