# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160602_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
