# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_picture_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='edited_image',
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_eight_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_five_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_four_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_nine_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_one_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_seven_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_six_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_ten_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_three_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='edit_two_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='picture',
            name='final_edited_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
