# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160606_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='edit_eight_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_five_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_four_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_nine_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_one_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_seven_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_six_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_ten_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_three_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='edit_two_image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='final_edited_image',
        ),
        migrations.AddField(
            model_name='picture',
            name='edited_image',
            field=models.ImageField(blank=True, upload_to='edited/'),
        ),
    ]
